name: Python application test with Github Actions

on:
  push:
    branches: [ test-ci ]
  pull_request:
    branches: [ test-ci ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd back-web-fortify
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        cd back-web-fortify/flaskr/tests
        python -m unittest discover -s .
